### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gdavila** [tracebox/tracebox#53]
Hi, I'm getting this bug when running the last commit. 

```
$ sudo tracebox  8.8.8.8
Segmentation fault (core dumped)
```

OS version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by oliviertilmans** [comment]
Hi,

Can you tell the version of tracebox, as printed at the bottom of the help message (tracebox -h) ?
Could you provide me the coredump/analyze it with gdb to get a stacktrace ? As I do not experience this issue, and it is not caught by travis either, it is hard to diagnose.

**Comment by gdavila** [comment]
I have not much experience with dbg tools. let me know if this is useful.

Tracebox version:
`Version: v0.4.2-2-g6b87f0d7339dcc9c` 

gdb:
```gdavila@mainserver:~/Downloads/tracebox/src/tracebox$ sudo gdb tracebox core
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from tracebox...done.
[New LWP 22723]

warning: Unexpected size of section `.reg-xstate/22723' in core file.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tracebox 8.8.8.8'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Unexpected size of section `.reg-xstate/22723' in core file.
#0  0x000000000045c2ce in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider (__a=..., __dat=<optimized out>, this=<optimized out>) at /usr/include/c++/5/bits/basic_string.h:109
109		: allocator_type(__a), _M_p(__dat) { }
(gdb) bt
#0  0x000000000045c2ce in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider (__a=..., __dat=<optimized out>, this=<optimized out>) at /usr/include/c++/5/bits/basic_string.h:109
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (
    __str=<error reading variable: Cannot access memory at address 0x28>, this=0x7fffa08c4720)
    at /usr/include/c++/5/bits/basic_string.h:399
#2  Crafter::Layer::GetName[abi:cxx11]() const (this=0x0) at crafter/Protocols/../Layer.h:251
#3  Crafter::ICMP::Craft (this=0x26ba850) at crafter/Protocols/ICMPCraft.cpp:163
#4  0x0000000000437828 in Crafter::Packet::Craft (this=this@entry=0x7fffa08c4870) at crafter/Packet.cpp:373
#5  0x0000000000437d1f in Crafter::Packet::GetRawPtr (this=this@entry=0x7fffa08c4870) at crafter/Packet.cpp:401
#6  0x000000000040961a in writePcap (p=p@entry=0x7fffa08c4870) at tracebox.cc:242
#7  0x000000000040a9b8 in doTracebox (pkt_shrd=std::shared_ptr (count 1, weak 0) 0x26be380, 
    callback=callback@entry=0x408c80 <Callback(void*, uint8_t, std::__cxx11::string&, PacketModifications*)>, err="", 
    ctx=ctx@entry=0x0) at tracebox.cc:537
#8  0x0000000000405deb in main (argc=<optimized out>, argv=0x7fffa08c4b88) at tracebox.cc:708

```

I also tried to run this version [da24a322ee-](https://github.com/tracebox/tracebox/tree/da24a322ee658b2a5f6466b0543abd99379c18b3), but I have the same issue.

**Comment by oliviertilmans** [comment]
This particular problem should no longer happen in
https://github.com/tracebox/tracebox/commit/752f69aeebd39fd8200954a92d324558f4575591

As it was caused by https://github.com/pellegre/libcrafter/commit/5cbd9cf24262f44c3defd33bb15b184a1a0ea21e

**Comment by gdavila** [comment]
Issue solved. Thanks a lot.
